package projet.carthagecreance_backend.Entity;

public enum RoleUtilisateur {
    SUPER_ADMIN,
    CHEF_DEPARTEMENT_DOSSIER,
    CHEF_DEPARTEMENT_RECOUVREMENT_AMIABLE,
    CHEF_DEPARTEMENT_RECOUVREMENT_JURIDIQUE,
    CHEF_DEPARTEMENT_FINANCE,
    AGENT_DOSSIER,
    AGENT_RECOUVREMENT_AMIABLE,
    AGENT_RECOUVREMENT_JURIDIQUE,
    AGENT_FINANCE
}
