package projet.carthagecreance_backend.Entity;

public enum TypeStatistique {
    TOTAL_DOSSIERS,
    DOSSIERS_EN_COURS,
    DOSSIERS_VALIDES,
    DOSSIERS_REJETES,
    DOSSIERS_CLOTURES,
    DOSSIERS_CREES_CE_MOIS,
    PERFORMANCE_AGENTS,
    PERFORMANCE_CHEFS,
    ENQUETES_COMPLETEES,
    ACTIONS_AMIABLES,
    AUDIENCES_PROCHAINES,
    TACHES_COMPLETEES,
    TACHES_EN_COURS,
    TAUX_REUSSITE_GLOBAL,
    MONTANT_RECOUVRE,
    MONTANT_EN_COURS
}
