package projet.carthagecreance_backend.Entity;

public enum TypeNotification {
    DOSSIER_CREE,
    DOSSIER_VALIDE,
    DOSSIER_REJETE,
    DOSSIER_EN_ATTENTE,
    DOSSIER_AFFECTE,
    DOSSIER_CLOTURE,
    ENQUETE_CREE,
    ENQUETE_VALIDE,
    ENQUETE_REJETE,
    ENQUETE_EN_ATTENTE,
    ACTION_AMIABLE_CREE,
    ACTION_AMIABLE_COMPLETEE,
    AUDIENCE_PROCHAINE,
    AUDIENCE_CREE,
    AUDIENCE_REPORTEE,
    TACHE_URGENTE,
    TACHE_AFFECTEE,
    TACHE_COMPLETEE,
    TRAITEMENT_DOSSIER,
    RAPPEL,
    INFO,
    NOTIFICATION_MANUELLE
}
